### ISSUE TITLE
userAgentId in step 7

### ISSUE THREAD

**Issue by nakulsolanki** [actions-on-google/actionssdk-smart-home-nodejs#62]
Not sure if this is the right place for this query. Step 7 in the Setup Instructions talks about configuring Request Sync. What should be the value of agentUserId for this curl POST ?
Also, should the api key for Step 6 be used here or should i create a new api key ?

**Comment by Fleker** [comment]
When you do a `SYNC` to the HomeGraph, one of the parameters you must include is an `agentUserId`. This is a string-based identifier for the user on your server. It could be an email address, auto-generated number, or anything else.

It should uniquely identify the user on your platform. When you do a `REQUEST_SYNC`, you should provide this value again so you'll receive a new `SYNC` request just for that user.

You should use the same API key, as it will work for all HomeGraph APIs.

In the future, questions about the API would probably fit better in StackOverflow since it is less an issue with this specific sample and those questions will surface better in search results.
